# Site Info
title: 'Nublando - a Blog about Cloud and Docker'
tagline: 'A Cloud and Docker Blog Site'
description: 'A Site Talking about Cloud,DevOps,and Docker. Made by <a href="http://github.com/proj4spes" target="_blank">@Proj4Spes</a>.'
baseurl: "/proj4spes.github.io"
url: https://proj4spes.github.io/proj4spes.github.io/
logo: '/public/logo.png'

# Site configurations
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Proj4Spes
  description: >
      A passionate <strong>Software Architect and DevOps</strong>, learning Cloud/AWS/DevOps/Ansible/Nomad/Terraform/Docker/Kubernetes
#  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/enrico-proietti-4a67392a?trk=hp-identity-name
    github:    http://github.com/proj4spes
    email:     http://www.google.com/recaptcha/mailhide/d?k=01Sq4O-dU1m3d82V_AMe90pg==&c=cIp0O4LvJ2TPJSfjXdY1TROPwjCA6vwmd5MRCGipNYc= 

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Download:
    - '/Download/'
  Github Project: 
    - 'http://github.com/proj4spes'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/cloud-1.jpg
  caption: The Cloud is pervasive .. although we do not realize.
  Intro: A Blog Site to Explain to myself Cloud Concepts . Cloud is a computing abstraction  to accomplish new processes and analisys on a huge amount of data, often generated by the Cloud itself, but it is also a set of tools can be used to improve the Cloud's behaviour  itself. So i'd like to understand iin deep how these tools operate and then back to understand how they can be used to modify the current  life's processes.
# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'proj4spes-github-io' # leave blank if you don't want disqus

